import { ScheduleItem } from "../types";

export const schedule: ScheduleItem[] = [
  {
    day: "Friday, November 14",
    time: "10:00 am - 6:00 pm",
    location: "Huang Foyer",
    url: "",
    description: "Check-In & Merch / Workshops TBD",
  },
  {
    day: "Friday, November 14",
    time: "6:00 pm - 7:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Dinner",
  },
  {
    day: "Friday, November 14",
    time: "7:00 pm - 8:15 pm",
    location: "Hewlett 200",
    url: "",
    description: "Opening Ceremony",
  },
  {
    day: "Friday, November 14",
    time: "8:15 pm - 9:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Team Formation",
  },
  {
    day: "Friday, November 14",
    time: "9:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Hacking Begins",
  },
  {
    day: "Saturday, November 15",
    time: "All day",
    location: "Huang Basement",
    url: "",
    description: "Hacking",
  },
  {
    day: "Saturday, November 15",
    time: "10:00 am - 1:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Brunch",
  },
  {
    day: "Saturday, November 15",
    time: "5:00 pm - 8:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Dinner",
  },
  {
    day: "Sunday, November 16",
    time: "9:00 am",
    location: "Huang Basement",
    url: "",
    description: "Hacking Ends",
  },
  {
    day: "Sunday, November 16",
    time: "10:00 am - 12:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Judging",
  },
  {
    day: "Sunday, November 16",
    time: "12:00 pm - 1:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Lunch",
  },
  {
    day: "Sunday, November 16",
    time: "2:00 pm - 3:00 pm",
    location: "Hewlett 200",
    url: "",
    description: "Closing Ceremony",
  },
  {
    day: "Sunday, November 16",
    time: "3:00 pm - 5:00 pm",
    location: "Huang Basement",
    url: "",
    description: "Expo / Recruitment / Open-Floor",
  },
];
